import { gql } from "@apollo/client";

export const GET_LISTING_BY_ID = gql`
  query GetListingById($raPid: Int!) {
    propertyByRaPid(raPid: $raPid ) {
    propertyType
    mrdType
    mlsStatus
    originalListPrice
    listPrice
    closePrice
    associationFee
    taxAnnualAmount
    taxYear
    daysOnMarket
    mlgCanView
    streetNumber
    streetDirPrefix
    streetName
    streetSuffix
    unitNumber
    city
    postalCode
    countyOrParish
    township
    roomsTotal
    bedroomsTotal
    bathroomsFull
    bathroomsHalf
    garageSpaces
    lotSizeAcres
    lotSizeDimensions
    livingArea
    mrdAge
    yearBuilt
    publicRemarks
    modificationTimestamp
    elementarySchool
    middleOrJuniorSchool
    highSchool
    elementarySchoolDistrict
    middleOrJuniorSchoolDistrict
    highSchoolDistrict
    listingAgreement
    waterfrontYn
    model
    mlsAreaMajor
    mrdActualstatus
    mrdActvDate
    mrdAsq
    mrdAssessorSqft
    mrdBb
    mrdBldgOnLand
    mrdBmd
    mrdBrbelow
    mrdCanOwnerRent
    mrdCurrentlyleased
    mrdDeedGarageCost
    mrdDin
    mrdDisabilityAccess
    mrdExt
    mrdFireplaceLocation
    mrdFullBathsBldg
    mrdGarageOnsite
    mrdGarageOwnership
    mrdGarageType
    mrdSpInclParking
    mrdHalfBathsBldg
    mrdIdx
    mrdLsz
    mrdMaf
    grossIncome
    additionalParcelsYn
    parcelNumber
    expirationDate
    listingId
  }
  }
`;
